### ISSUE TITLE
Upgrade to 3.0.1 (or 3.0.2) issue

### ISSUE THREAD

**Issue by jamtur01** [opentok/OpenTok-Ruby-SDK#157]
Updated Gemfile for 3.0.1 (tried 3.0.2 also) and when I try to load the gem I get:

```
rails aborted!
LoadError: cannot load such file -- digest/hmac
/home/circleci/backend_app/vendor/bundle/ruby/2.4.0/gems/bootsnap-1.1.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:19:in `require'
/home/circleci/backend_app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292:in `block in require'
/home/circleci/backend_app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:258:in `load_dependency'
/home/circleci/backend_app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292:in `require'
/home/circleci/backend_app/vendor/bundle/ruby/2.4.0/gems/opentok-2.2.2/lib/opentok/token_generator.rb:6:in `<main>'
/home/circleci/backend_app/vendor/bundle/ruby/2.4.0/gems/bootsnap-1.1.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
/home/circleci/backend_app/vendor/bundle/ruby/2.4.0/gems/bootsnap-1.1.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
/home/circleci/backend_app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292:in `block in require'
/home/circleci/backend_app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:258:in `load_dependency'
/home/circleci/backend_app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292:in `require'
/home/circleci/backend_app/vendor/bundle/ruby/2.4.0/gems/opentok-2.2.2/lib/opentok/session.rb:2:in `<main>'
/home/circleci/backend_app/vendor/bundle/ruby/2.4.0/gems/bootsnap-1.1.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
/home/circleci/backend_app/vendor/bundle/ruby/2.4.0/gems/bootsnap-1.1.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
/home/circleci/backend_app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292:in `block in require'
/home/circleci/backend_app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:258:in `load_dependency'
/home/circleci/backend_app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292:in `require'
/home/circleci/backend_app/vendor/bundle/ruby/2.4.0/gems/opentok-2.2.2/lib/opentok/opentok.rb:2:in `<main>'
/home/circleci/backend_app/vendor/bundle/ruby/2.4.0/gems/bootsnap-1.1.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
/home/circleci/backend_app/vendor/bundle/ruby/2.4.0/gems/bootsnap-1.1.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
/home/circleci/backend_app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292:in `block in require'
/home/circleci/backend_app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:258:in `load_dependency'
/home/circleci/backend_app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292:in `require'
/home/circleci/backend_app/vendor/bundle/ruby/2.4.0/gems/opentok-2.2.2/lib/opentok.rb:2:in `<main>'
/home/circleci/backend_app/vendor/bundle/ruby/2.4.0/gems/bootsnap-1.1.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:50:in `require'
/home/circleci/backend_app/vendor/bundle/ruby/2.4.0/gems/bootsnap-1.1.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:50:in `require'
/home/circleci/backend_app/config/application.rb:18:in `<main>'
/home/circleci/backend_app/Rakefile:4:in `require_relative'
/home/circleci/backend_app/Rakefile:4:in `<main>'
/home/circleci/backend_app/vendor/bundle/ruby/2.4.0/gems/bootsnap-1.1.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `load'
/home/circleci/backend_app/vendor/bundle/ruby/2.4.0/gems/bootsnap-1.1.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `load'
/home/circleci/backend_app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:286:in `block in load'
/home/circleci/backend_app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:258:in `load_dependency'
/home/circleci/backend_app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:286:in `load'
/home/circleci/backend_app/vendor/bundle/ruby/2.4.0/gems/railties-5.1.4/lib/rails/commands/rake/rake_command.rb:20:in `block in perform'
/home/circleci/backend_app/vendor/bundle/ruby/2.4.0/gems/railties-5.1.4/lib/rails/commands/rake/rake_command.rb:18:in `perform'
/home/circleci/backend_app/vendor/bundle/ruby/2.4.0/gems/railties-5.1.4/lib/rails/command.rb:46:in `invoke'
/home/circleci/backend_app/vendor/bundle/ruby/2.4.0/gems/railties-5.1.4/lib/rails/commands.rb:16:in `<main>'
/home/circleci/backend_app/vendor/bundle/ruby/2.4.0/gems/bootsnap-1.1.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
/home/circleci/backend_app/vendor/bundle/ruby/2.4.0/gems/bootsnap-1.1.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
/home/circleci/backend_app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292:in `block in require'
/home/circleci/backend_app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:258:in `load_dependency'
/home/circleci/backend_app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292:in `require'
bin/rails:6:in `<main>'
```

Following the stacktrace bouncing ball we get: https://github.com/opentok/OpenTok-Ruby-SDK/blob/master/lib/opentok/token_generator.rb#L6

I found #79 but I'm using Ruby 2.4.2 and this shouldn't be an issue....

The only change I can see between 3.0.0 and 3.0.1 seems to be: https://github.com/opentok/OpenTok-Ruby-SDK/commit/e2e43ed89865c539cabc10e65634f7fcb1a0e777 - in which Yard's version is bumped.

We've not changed Ruby versions or anything else that I can see.

**Comment by jamtur01** [comment]
Wait. Ignore me. It appears opentok 2.2 is being vendored here.
