### ISSUE TITLE
Ruby SDK is broken on Ruby 2.2

### ISSUE THREAD

**Issue by luma** [opentok/Opentok-Ruby-SDK#83]
Because digest/hmac is removed from Ruby 2.2, it's recommended that OpenSSL::HMAC is used instead.

```
/Users/rollyfordham/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- digest/hmac (LoadError)
	from /Users/rollyfordham/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/rollyfordham/.rvm/gems/ruby-2.2.0/gems/opentok-2.2.3/lib/opentok/token_generator.rb:6:in `<top (required)>'
	from /Users/rollyfordham/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/rollyfordham/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/rollyfordham/.rvm/gems/ruby-2.2.0/gems/opentok-2.2.3/lib/opentok/session.rb:2:in `<top (required)>'
	from /Users/rollyfordham/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/rollyfordham/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/rollyfordham/.rvm/gems/ruby-2.2.0/gems/opentok-2.2.3/lib/opentok/opentok.rb:2:in `<top (required)>'
	from /Users/rollyfordham/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/rollyfordham/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/rollyfordham/.rvm/gems/ruby-2.2.0/gems/opentok-2.2.3/lib/opentok.rb:2:in `<top (required)>'
	from /Users/rollyfordham/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `require'
	from /Users/rollyfordham/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
	from /Users/rollyfordham/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:39:in `require'
	from /Users/rollyfordham/bin/generate_session:3:in `<main>'
```

**Comment by aoberoi** [comment]
thanks for reporting @luma. this is a dup of #79. the changes are already merged into master, but i haven't done a release since then. sounds like i should make one soon :smile:. urgent?

**Comment by luma** [comment]
Nice! Nah, I just hit it myself and only scanned the first page of issues so I didn’t notice that you’re way ahead of me. I have Ruby 2.0 installed as well so it isn’t a blocker for me.




:-)

**Comment by aoberoi** [comment]
gotcha. i'll stamp out a release this week. it looks like there's a couple more PRs that could be merged in too so its a good time.
